### ISSUE TITLE
Benchmark Other Circuit Discovery Algorithms

### ISSUE THREAD

**Issue by cybershiptrooper** [FlyingPumba/circuits-benchmark#5]
This should include at least:
1. Subnetwork Probing
2. DAS

Need to plan how to compare DAS with others. 

Other algorithms we can consider:
1. Edge-wise Attribution Patching

**Comment by FlyingPumba** [comment]
We are using auto-circuit which has EAP. SP has been included from ACDC repo. DAS will be added when we support subspaces.
